### ISSUE TITLE
Lightroom Plug-in?

### ISSUE THREAD

**Issue by tomegel** [brianbillman/exif-lens-chooser#1]
Hi Brian,
Thanks for creating this.  I was able to get it working per your instructions and then began thinking of ways to make improve the workflow.  One idea was to add an action in the Automator to use images selected in Lightroom instead of having to drag them over to the app.  It was the first time I have used the Automator, but did not see an easy way to add custom actions.  The other idea was to make this a LR plug-in.  Do you have any thoughts on the feasibility of either of these two options?

Thanks,
Tom

**Comment by brianbillman** [comment]
Hi Tom,

Thanks for the feedback.  I'll try poking around this holiday season when I have some downtime to see how difficult either of these options might be.  I did find a separate LR plugin that was similar ([LensTagger](http://www.essl.de/wp/software/lenstagger-lightroom-plugin/)), but I never spent much time with it, and it was probably about a year ago, might be worth a look.

**Comment by tomegel** [comment]
Hi Brian,
I'm not sure if you are still supporting this, but the latest version is not working for me.  I get the message: EXIF Update Complete. Success! Files Updated: 0.  So it doesn't seem to be writing to the file.  I tried debugging in automator. Everything looks good up until the last step (run shel script) which returns empty.  Any ideas?

Thanks,
Tom

**Comment by brianbillman** [comment]
Hi Tom,

I've abandoned the AppleScript/Automator version of this (I think something broke with it with Mac OS Sierra maybe?), but I replaced it with a bash script-only version (which is on a separate branch on the github repo named `script-only` - I just changed it to be the default branch so you see it when it comes up, the README is updated as well).  It does essentially the same thing, but provides a prompt in a Terminal window for which lens.  Its easier to keep up to date, and you can run it in multiple terminal windows at once, so you can get through multiple lenses quicker.  

Give it a try and let me know if you have any questions!

**Comment by tomegel** [comment]
Hi Brian,
Thanks for the quick reply.  I was able to get the script-only version
running, but it doesn't seem to be writing the exif data correctly (still
shows 0.0mm f/0.0).  Here's what the terminal window shows:

Last login: Mon Nov 20 12:34:59 on ttys000
Toms-MBP-wifi:~ tomegel$ exif-lens-chooser.sh /Volumes/G-DRIVE\ mobile\
USB-C/PhotoLibrary/2017/2017-03-16/_TE21934.NEF

Lens Options:
1) Nikkor 20 mm f/2.8 AIS    7) Micro-Nikkor 55 mm f/2.8 AIS
2) Nikkor 24 mm f/2.8 AIS    8) Micro-Nikkor 55 mm f/3.5 AI
3) Nikkor 28 mm f/2.8 AIS    9) Nikkor 85 mm f/1.8 AIS
4) Nikkor-O 35 mm f/2.0 AIS   10) Nikkor 105 mm f/2.5 AIS
5) Nikkor 50 mm f/1.2 AIS   11) Micro-Nikkor 105 mm f/4 AIS
6) Nikkor 50 mm f/1.8 AIS

    Enter choice: 1

    Selected lens: Nikkor 20 mm f/2.8 AIS

    Proceeed with selected lens? (y)es, (n)o, or (q)uit: y

EXIF Update Complete
Success!
Files updated: 0
/usr/local/bin/exif-lens-chooser.sh: line 716: type: terminal-notifier: not
found

Any ideas?

Thanks,
Tom

**Comment by tomegel** [comment]
Hi Brian,
I was able to install terminal-notifier, but still get an error:

EXIF Update Complete
Success!
Files updated: 0
2017-11-20 15:48:31.642 terminal-notifier[12307:4134279] No Info.plist file
in application bundle or no NSPrincipalClass in the Info.plist file, exiting

Any help is appreciated.

Thanks,
Tom

**Comment by brianbillman** [comment]
Tom, can you post the output of `~/exif-lens-chooser.txt`?  You can do so in terminal by running the following:

~~~
cat ~/exif-lens-chooser.txt
~~~

I can provide some more debugging tips tomorrow or Wednesday.   Thanks.

**Comment by tomegel** [comment]
Hi Brian,
Here is the output:

ast login: Mon Nov 20 15:35:36 on ttys000
Toms-MBP:~ tomegel$ cat ~/exif-lens-chooser.txt
/Volumes/G-DRIVE mobile USB-C/PhotoLibrary/2017/2017-03-16/_TE21934.NEF =
ExifTool Version Number : 10.67
File Name : _TE21934.NEF
Directory : /Volumes/G-DRIVE mobile USB-C/PhotoLibrary/2017/2017-03-16
File Size : 34 MB
File Modification Date/Time : 2017:03:16 19:30:52-04:00
File Access Date/Time : 2017:11:20 15:48:31-05:00
File Inode Change Date/Time : 2017:07:24 22:42:11-04:00
File Permissions : rwxrwxrwx
File Type : NEF
File Type Extension : nef
MIME Type : image/x-nikon-nef
Exif Byte Order : Big-endian (Motorola, MM)
Make : NIKON CORPORATION
Camera Model Name : NIKON Df
Orientation : Rotate 270 CW
Software : Ver.1.01
Modify Date : 2017:03:16 19:30:19
Artist :
Jpg From Raw Start : 1226752
Jpg From Raw Length : 1388132
Y Cb Cr Positioning : Co-sited
Image Width : 4992
Image Height : 3292
Bits Per Sample : 14
Compression : Uncompressed
Photometric Interpretation : Color Filter Array
Strip Offsets : (Binary data 4816 bytes, use -b option to extract)
Samples Per Pixel : 1
Rows Per Strip : 6
Strip Byte Counts : (Binary data 3293 bytes, use -b option to extract)
X Resolution : 300
Y Resolution : 300
Planar Configuration : Chunky
Resolution Unit : inches
CFA Repeat Pattern Dim : 2 2
CFA Pattern 2 : 0 1 1 2
Subfile Type : Reduced-resolution image
Other Image Start : 194048
Other Image Length : 1032275
Reference Black White : 0 255 0 255 0 255
Copyright : Tom Egel
Exposure Time : 30
F Number : 11.0
Exposure Program : Manual
ISO : 100
Sensitivity Type : Recommended Exposure Index
Create Date : 2017:03:16 19:30:19
Exposure Compensation : -2/3
Max Aperture Value : 1.0
Metering Mode : Multi-segment
Light Source : Unknown
Flash : No Flash
Focal Length : 20.0 mm
Maker Note Version : 2.11
Quality : RAW
White Balance : Auto1
Focus Mode : Manual
Flash Setting :
Flash Type :
White Balance Fine Tune : 1 -1
WB RB Levels : 1.40625 2.1875 1 1
Program Shift : 0
Exposure Difference : +5.3
Preview Image Start : 26188
Preview Image Length : 105079
ISO Setting : 100
External Flash Exposure Comp : 0
Flash Exposure Bracket Value : 0.0
Exposure Bracket Value : 0
Crop Hi Speed : Off (4992x3292 cropped to 4992x3292 at pixel 0,0)
Exposure Tuning : 0
Serial Number : 3000306
Color Space : Adobe RGB
VR Info Version : 0100
Vibration Reduction : Off
VR Mode : Normal
Active D-Lighting : Normal
Picture Control Version : 0100
Picture Control Name : Standard
Picture Control Base : Standard
Picture Control Adjust : Default Settings
Picture Control Quick Adjust : Normal
Brightness : Normal
Hue Adjustment : None
Filter Effect : n/a
Toning Effect : n/a
Toning Saturation : n/a
Time Zone : -05:00
Daylight Savings : Yes
Date Display Format : M/D/Y
ISO Expansion : Off
ISO2 : 100
ISO Expansion 2 : Off
Vignette Control : Off
Auto Distortion Control : Off
Lens Type : MF
Lens : 0mm f/0
Flash Mode : Did Not Fire
Shooting Mode : Single-Frame
Contrast Curve : (Binary data 578 bytes, use -b option to extract)
Shot Info Version : 0228
Firmware Version : 1.01a
Noise Reduction : Off
Color Balance Version : 0220
Lens Data Version : 0204
Exit Pupil Position : 0.0 mm
AF Aperture : 1.0
Focus Position : 0x00
Focus Distance : 0.01 m
Lens ID Number : 0
Lens F Stops : 0.00
Min Focal Length : 5.0 mm
Max Focal Length : 5.0 mm
Max Aperture At Min Focal : 1.0
Max Aperture At Max Focal : 1.0
MCU Version : 0
Effective Max Aperture : 4.0
Raw Image Center : 2472 1646
Retouch History : None
Shutter Count : 2287
Flash Info Version : 0106
Multi Exposure Version : 0100
Multi Exposure Mode : Off
Multi Exposure Shots : 0
Multi Exposure Auto Gain : Off
High ISO Noise Reduction : Off
Power Up Time : 0000:00:00 00:00:00
AF Info 2 Version : 0100
Contrast Detect AF : Off
AF Area Mode : Single Area
Phase Detect AF : Off
Primary AF Point : (none)
AF Points Used : (none)
Contrast Detect AF In Focus : No
File Info Version : 0100
Memory Card Number : 0
Directory Number : 100
File Number : 1934
AF Fine Tune : Off
AF Fine Tune Index : n/a
AF Fine Tune Adj : 0
Retouch Info Version : 0200
Retouch NEF Processing : Off
User Comment :
Sub Sec Time : 70
Sub Sec Time Original : 70
Sub Sec Time Digitized : 70
Sensing Method : One-chip color area
File Source : Digital Camera
Scene Type : Directly photographed
Custom Rendered : Normal
Exposure Mode : Manual
Digital Zoom Ratio : 1
Focal Length In 35mm Format : 20 mm
Scene Capture Type : Standard
Gain Control : None
Contrast : Normal
Saturation : Normal
Sharpness : Normal
Subject Distance Range : Unknown
GPS Version ID : 2.3.0.0
Date/Time Original : 2017:03:16 19:30:19
TIFF-EP Standard ID : 1 0 0 0
Aperture : 11.0
Auto Focus : Off
Blue Balance : 2.1875
CFA Pattern : [Red,Green][Green,Blue]
Image Size : 4992x3292
Jpg From Raw : (Binary data 1388132 bytes, use -b option to extract)
Lens ID : Manual Lens No CPU
Lens Spec : 0mm f/0 MF
Megapixels : 16.4
Other Image : (Binary data 1032275 bytes, use -b option to extract)
Preview Image : (Binary data 105079 bytes, use -b option to extract)
Red Balance : 1.40625
Scale Factor To 35 mm Equivalent: 1.0
Shutter Speed : 30
Create Date : 2017:03:16 19:30:19.70
Date/Time Original : 2017:03:16 19:30:19.70
Modify Date : 2017:03:16 19:30:19.70
Thumbnail TIFF : (Binary data 57816 bytes, use -b option to extract)
Circle Of Confusion : 0.030 mm
Depth Of Field : -0.00 m (0.01 - 0.01 m)
Field Of View : 84.0 deg (0.02 m)
Focal Length : 20.0 mm (35 mm equivalent: 20.0 mm)
Hyperfocal Distance : 1.21 m
Light Value : 2.0

**Comment by brianbillman** [comment]
It looks like something is wrong in the arguments to exiftool, because the output you're getting is what would be expected if you just ran `exiftool image.nef`, where it lists out all the properties.  Try this:

1. Open `exif-lens-chooser.sh` in a text editor, and search for `cmd=`.  You should see a line that looks like this: `cmd="exiftool -overwrite_original $lens_params $focalLength35mmParam $nonNikonParam \"$file\" 2>&1"`.
2. On the next line, add the following (above the `RESULT=...` line):
```
echo "----------"
echo "$cmd"
echo "----------"
```

Paste back what is output between the dashed lines.  The formatting will be pretty messed up to a bunch of spaces between some of the command arguments.  You should be able to pretty much run that command directly, and it would update that one file.  My feeling is that something isn't escaped correctly, which is cause it to not update the file, but I will have to see it to determine how to best handle.

**Comment by tomegel** [comment]
Hi Brian,
Thanks for your help. I was able to find the issue.  The text editor I was
using was inserting the wrong kind of single quote.

All is well now.

Thanks,
Tom

**Comment by brianbillman** [comment]
Glad to hear it got sorted out!
